### ISSUE TITLE
Ideas for new features and projects

### ISSUE THREAD

**Issue by Ellzord** [Ellzord/JALSE#103]
See https://github.com/Ellzord/JALSE/wiki/Future-changes

Can we get some suggestions of what you would like to see?

**Comment by Ellzord** [comment]
@benwaffle @wlmiller @pbremer @mariosk89 @ckerr89 @stelioskiayias

**Comment by mariosk89** [comment]
I'd say that having a number of well-known simulation projects will be good for a start. Robomop and  Termites simulations can act as a nice tutorial, because the goal of the simulation is simple and easy to understand. Based on this, we can have tutorials matching the steps required to build a JALSE project, to the steps required by the simulation.

After this, we could have a bigger simulation running over the web.
This would require a JALSE RESTful wrapper

**Comment by Ellzord** [comment]
Taking this in mind + Reddit post
